"""
KaggleBoost DEMO — Step-by-step pipeline walkthrough
Runs ONLY the Yahoo Finance scraper (fastest, no API key needed).
Shows exactly what happens at each stage: Scrape → Clean → Package → (would Upload)
"""

import os, sys, json
from pathlib import Path
from datetime import datetime

# Windows UTF-8 fix
if sys.stdout.encoding and sys.stdout.encoding.lower() not in ("utf-8", "utf8"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

sys.path.insert(0, str(Path(__file__).parent))

from scrapers.stock_market import StockMarketScraper
from processors.cleaner import DataCleaner
from processors.packager import DatasetPackager

DEMO_DIR = Path("tmp/demo")
DEMO_DIR.mkdir(parents=True, exist_ok=True)
Path("logs").mkdir(exist_ok=True)

SEP  = "=" * 60
STEP = lambda n, t: print(f"\n{SEP}\n  STEP {n}: {t}\n{SEP}")

# ─── STEP 1: SCRAPE ──────────────────────────────────────────────
STEP(1, "SCRAPE — Fetching real stock data from Yahoo Finance")

scraper = StockMarketScraper()
print(f"  Scraper: {scraper.name}")
print("  Downloading 5y OHLCV data for top tech stocks...")

# Use only 3 tickers for the demo (faster)
import yfinance as yf
import pandas as pd

demo_tickers = ["AAPL", "TSLA", "NVDA"]
frames = []
for ticker in demo_tickers:
    t = yf.Ticker(ticker)
    hist = t.history(period="1y", interval="1d")  # 1y for speed
    hist = hist.reset_index()
    hist["ticker"] = ticker
    hist.columns = [c.lower().replace(" ", "_") for c in hist.columns]
    frames.append(hist)
    print(f"    OK {ticker}: {len(hist)} rows fetched")

raw_df = pd.concat(frames, ignore_index=True)
cols = ["ticker"] + [c for c in raw_df.columns if c != "ticker"]
raw_df = raw_df[cols]

print(f"\n  RAW DATA SHAPE: {raw_df.shape[0]} rows x {raw_df.shape[1]} columns")
print(f"  Columns: {list(raw_df.columns)}")
print(f"\n  First 3 rows:")
print(raw_df.head(3).to_string(index=False, max_cols=7))

dataset_info = {
    "id": "demo_tech_stocks_1y",
    "title": "Demo: Top 3 Tech Stocks — 1-Year OHLCV",
    "description": "1-year daily OHLCV data for AAPL, TSLA, NVDA. Generated by KaggleBoost demo.",
    "tags": ["stocks", "finance", "demo", "machine-learning"],
    "license": "Yahoo Finance Terms (for research/educational use)",
    "source": "Yahoo Finance via yfinance",
    "dataframe": raw_df,
    "filename": "demo_tech_stocks_1y.csv",
    "config": {"remove_nulls": False},
}

# ─── STEP 2: CLEAN ───────────────────────────────────────────────
STEP(2, "CLEAN — Remove nulls, fix types, deduplicate")

cleaner = DataCleaner()
cleaned_df = cleaner.clean(raw_df, {"remove_nulls": False})
dataset_info["dataframe"] = cleaned_df

null_before = raw_df.isnull().sum().sum()
null_after  = cleaned_df.isnull().sum().sum()
dups_before = raw_df.duplicated().sum()
dups_after  = cleaned_df.duplicated().sum()

print(f"  Rows before clean : {len(raw_df)}")
print(f"  Rows after  clean : {len(cleaned_df)}")
print(f"  Null values removed   : {null_before - null_after}")
print(f"  Duplicate rows removed: {dups_before - dups_after}")
print(f"  Data types:")
for col, dtype in cleaned_df.dtypes.items():
    print(f"    {col:<25} {dtype}")

# ─── STEP 3: PACKAGE ─────────────────────────────────────────────
STEP(3, "PACKAGE — Build Kaggle-uploadable folder")

packager = DatasetPackager()
os.environ.setdefault("KAGGLE_USERNAME", "shivansh7275")  # demo default
package_path = packager.package(dataset_info, DEMO_DIR)

print(f"  Package created at: {package_path}")
print(f"\n  Files inside package:")
for f in sorted(package_path.iterdir()):
    size = f.stat().st_size
    size_str = f"{size/1024:.1f} KB" if size > 1024 else f"{size} B"
    print(f"    {f.name:<35} {size_str}")

# Show the metadata JSON that Kaggle reads
meta_path = package_path / "dataset-metadata.json"
print(f"\n  dataset-metadata.json content (what Kaggle sees):")
print("  " + "-"*50)
meta = json.loads(meta_path.read_text())
print(json.dumps(meta, indent=4))

# Show first 5 lines of README
readme_path = package_path / "README.md"
lines = readme_path.read_text(encoding="utf-8").splitlines()
print(f"\n  README.md preview (first 12 lines):")
print("  " + "-"*50)
for line in lines[:12]:
    print(f"  {line}")
print("  ...")

# ─── STEP 4: UPLOAD (dry run) ────────────────────────────────────
STEP(4, "UPLOAD — (DRY RUN — no real upload)")

kaggle_ref = f"shivansh7275/{dataset_info['id'].replace('_','-')}"
kaggle_url = f"https://www.kaggle.com/datasets/{kaggle_ref}"
print(f"  Would run: kaggle datasets create -p {package_path} --dir-mode zip")
print(f"  Target   : {kaggle_url}")
print(f"  Dataset  : {dataset_info['title']}")
print(f"  Size     : {len(cleaned_df)} rows, {len(cleaned_df.columns)} columns")

# ─── SUMMARY ─────────────────────────────────────────────────────
print(f"\n{'='*60}")
print("  PIPELINE COMPLETE!")
print(f"{'='*60}")
print(f"  Scraper  : {scraper.name}")
print(f"  Rows     : {len(cleaned_df):,}")
print(f"  Package  : {package_path}")
print(f"  Kaggle   : {kaggle_url}  [would upload here]")
print(f"\n  In GitHub Actions this runs every 3 days automatically.")
print(f"  All scrapers (WorldBank, NASA, OWID, IndiaGov + Stocks)")
print(f"  would produce ~5-10 datasets per run uploaded to:")
print(f"  https://www.kaggle.com/shivansh7275")
